; ==============================================================================
;  SENTINEL-X — Configuration PlatformIO
;  Cible : ESP8266 NodeMCU v3 (ESP-12E)
; ==============================================================================

[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Vitesse du port série (doit correspondre à Serial.begin(115200) dans main.cpp)
monitor_speed = 115200

; Vitesse de flashage (460800 = rapide, réduire à 115200 si erreurs de téléversement)
upload_speed = 460800

; Bibliothèques utilisées par le projet
; Ajoutez ici si vous intégrez un nouveau capteur ou une nouvelle bibliothèque.
lib_deps =
; Écran OLED
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9

; Capteur DHT22 (température / humidité)
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; Sérialisation JSON (payloads vers le serveur)
    bblanchon/ArduinoJson@^7.0.0

; WebSocket (réception des commandes depuis le Dashboard)
    links2004/WebSockets@^2.4.1